## Importing Libraries


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()


## About Data


Data Source : https://www.kaggle.com/datasets/rodsaldanha/arketing-campaign


- AcceptedCmp1 - 1 if customer accepted the offer in the 1st campaign, 0 otherwise
- AcceptedCmp2 - 1 if customer accepted the offer in the 2nd campaign, 0 otherwise
- AcceptedCmp3 - 1 if customer accepted the offer in the 3rd campaign, 0 otherwise
- AcceptedCmp4 - 1 if customer accepted the offer in the 4th campaign, 0 otherwise
- AcceptedCmp5 - 1 if customer accepted the offer in the 5th campaign, 0 otherwise
- Response (target) - 1 if customer accepted the offer in the last campaign, 0 otherwise
- Complain - 1 if customer complained in the last 2 years
- DtCustomer - date of customer’s enrolment with the company
- Education - customer’s level of education
- Marital - customer’s marital status
- Kidhome - number of small children in customer’s household
- Teenhome - number of teenagers in customer’s household
- Income - customer’s yearly household income
- MntFishProducts - amount spent on fish products in the last 2 years
- MntMeatProducts - amount spent on meat products in the last 2 years
- MntFruits - amount spent on fruits products in the last 2 years
- MntSweetProducts - amount spent on sweet products in the last 2 years
- MntWines - amount spent on wine products in the last 2 years
- MntGoldProds - amount spent on gold products in the last 2 years
- NumDealsPurchases - number of purchases made with discount
- NumCatalogPurchases - number of purchases made using catalogue
- NumStorePurchases - number of purchases made directly in stores
- NumWebPurchases - number of purchases made through company’s web site
- NumWebVisitsMonth - number of visits to company’s web site in the last month
- Recency - number of days since the last purchase


## Load Dataset


In [2]:
data = pd.read_csv('data/marketing_campaign.csv', delimiter=';')
data.head()


ID  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0  5524        1957  Graduation         Single  58138.0        0         0   
1  2174        1954  Graduation         Single  46344.0        1         1   
2  4141        1965  Graduation       Together  71613.0        0         0   
3  6182        1984  Graduation       Together  26646.0        1         0   
4  5324        1981         PhD        Married  58293.0        1         0   

  Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  AcceptedCmp3  \
0  2012-09-04       58       635  ...                  7             0   
1  2014-03-08       38        11  ...                  5             0   
2  2013-08-21       26       426  ...                  4             0   
3  2014-02-10       26        11  ...                  6             0   
4  2014-01-19       94       173  ...                  5             0   

   AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  \
0             0             0             0             0         0   
1             0             0             0             0         0   
2             0             0             0             0         0   
3             0             0             0             0         0   
4             0             0             0             0         0   

   Z_CostContact  Z_Revenue  Response  
0              3         11         1  
1              3         11         0  
2              3         11         0  
3              3         11         0  
4              3         11         0  

[5 rows x 29 columns]

## Exploratory Data Analysis


In [3]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ID                   2240 non-null   int64  
 1   Year_Birth           2240 non-null   int64  
 2   Education            2240 non-null   object 
 3   Marital_Status       2240 non-null   object 
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64  
 6   Teenhome             2240 non-null   int64  
 7   Dt_Customer          2240 non-null   object 
 8   Recency              2240 non-null   int64  
 9   MntWines             2240 non-null   int64  
 10  MntFruits            2240 non-null   int64  
 11  MntMeatProducts      2240 non-null   int64  
 12  MntFishProducts      2240 non-null   int64  
 13  MntSweetProducts     2240 non-null   int64  
 14  MntGoldProds         2240 non-null   int64  
 15  NumDealsPurchases    2240 non-null   i

In [4]:
print("Unique values in Education column:", data['Education'].unique())
print("Unique values in Marital_Status column:",
      data['Marital_Status'].unique())


Unique values in Education column: ['Graduation' 'PhD' 'Master' 'Basic' '2n Cycle']
Unique values in Marital_Status column: ['Single' 'Together' 'Married' 'Divorced' 'Widow' 'Alone' 'Absurd' 'YOLO']


In [5]:
# summarizing education column

def education_level(education):
    if education in ['Graduation', 'PhD', 'Master']:
        return 'High'
    elif education in ['Basic']:
        return 'Middle'
    else:
        return 'Low'


data['Education_Level'] = data['Education'].apply(education_level)
data = data.drop('Education', axis=1)


In [6]:
# summarizing marital_status column

def living_status(marital_status):
    if marital_status in ['Alone', 'Absurd', 'YOLO']:
        return 'Living Alone'
    else:
        return 'Living with Others'


data['Living_Status'] = data['Marital_Status'].apply(living_status)
data = data.drop('Marital_Status', axis=1)


In [7]:
# Calculating customer age

data['Age'] = 2023 - data['Year_Birth']
data = data.drop('Year_Birth', axis=1)
data.head()


ID   Income  Kidhome  Teenhome Dt_Customer  Recency  MntWines  MntFruits  \
0  5524  58138.0        0         0  2012-09-04       58       635         88   
1  2174  46344.0        1         1  2014-03-08       38        11          1   
2  4141  71613.0        0         0  2013-08-21       26       426         49   
3  6182  26646.0        1         0  2014-02-10       26        11          4   
4  5324  58293.0        1         0  2014-01-19       94       173         43   

   MntMeatProducts  MntFishProducts  ...  AcceptedCmp5  AcceptedCmp1  \
0              546              172  ...             0             0   
1                6                2  ...             0             0   
2              127              111  ...             0             0   
3               20               10  ...             0             0   
4              118               46  ...             0             0   

   AcceptedCmp2  Complain  Z_CostContact  Z_Revenue  Response  \
0             0         0              3         11         1   
1             0         0              3         11         0   
2             0         0              3         11         0   
3             0         0              3         11         0   
4             0         0              3         11         0   

   Education_Level       Living_Status  Age  
0             High  Living with Others   66  
1             High  Living with Others   69  
2             High  Living with Others   58  
3             High  Living with Others   39  
4             High  Living with Others   42  

[5 rows x 29 columns]

In [8]:
# Replacing blank rows with mean of income values

data['Income'] = data['Income'].fillna(data['Income'].mean())
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ID                   2240 non-null   int64  
 1   Income               2240 non-null   float64
 2   Kidhome              2240 non-null   int64  
 3   Teenhome             2240 non-null   int64  
 4   Dt_Customer          2240 non-null   object 
 5   Recency              2240 non-null   int64  
 6   MntWines             2240 non-null   int64  
 7   MntFruits            2240 non-null   int64  
 8   MntMeatProducts      2240 non-null   int64  
 9   MntFishProducts      2240 non-null   int64  
 10  MntSweetProducts     2240 non-null   int64  
 11  MntGoldProds         2240 non-null   int64  
 12  NumDealsPurchases    2240 non-null   int64  
 13  NumWebPurchases      2240 non-null   int64  
 14  NumCatalogPurchases  2240 non-null   int64  
 15  NumStorePurchases    2240 non-null   i

In [9]:
# Calculation of Customer Age

data['Dt_Customer'] = data['Dt_Customer'].astype('datetime64[ns]')
data['Cust_Age'] = ((pd.to_datetime(
    'now') - pd.to_datetime(data['Dt_Customer'])) / np.timedelta64(1, 'Y')).astype('int64')
data = data.drop('Dt_Customer', axis=1)
data.head()


ID   Income  Kidhome  Teenhome  Recency  MntWines  MntFruits  \
0  5524  58138.0        0         0       58       635         88   
1  2174  46344.0        1         1       38        11          1   
2  4141  71613.0        0         0       26       426         49   
3  6182  26646.0        1         0       26        11          4   
4  5324  58293.0        1         0       94       173         43   

   MntMeatProducts  MntFishProducts  MntSweetProducts  ...  AcceptedCmp1  \
0              546              172                88  ...             0   
1                6                2                 1  ...             0   
2              127              111                21  ...             0   
3               20               10                 3  ...             0   
4              118               46                27  ...             0   

   AcceptedCmp2  Complain  Z_CostContact  Z_Revenue  Response  \
0             0         0              3         11         1   
1             0         0              3         11         0   
2             0         0              3         11         0   
3             0         0              3         11         0   
4             0         0              3         11         0   

   Education_Level       Living_Status  Age  Cust_Age  
0             High  Living with Others   66        10  
1             High  Living with Others   69         9  
2             High  Living with Others   58         9  
3             High  Living with Others   39         9  
4             High  Living with Others   42         9  

[5 rows x 29 columns]

In [10]:
# reordering columns

column_names = ['ID', 'Income', 'Kidhome', 'Teenhome', 'Recency', 'MntWines',
                'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
                'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
                'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
                'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
                'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response',
                'Education_Level', 'Living_Status', 'Age', 'Cust_Age']

column_names_reordered = ['ID', 'Education_Level', 'Living_Status', 'Age', 'Cust_Age', 'Income', 'Kidhome', 'Teenhome', 'Recency', 'MntWines',
                          'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
                          'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
                          'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
                          'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
                          'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response']

data = data[column_names_reordered]

data.head()


ID Education_Level       Living_Status  Age  Cust_Age   Income  Kidhome  \
0  5524            High  Living with Others   66        10  58138.0        0   
1  2174            High  Living with Others   69         9  46344.0        1   
2  4141            High  Living with Others   58         9  71613.0        0   
3  6182            High  Living with Others   39         9  26646.0        1   
4  5324            High  Living with Others   42         9  58293.0        1   

   Teenhome  Recency  MntWines  ...  NumWebVisitsMonth  AcceptedCmp3  \
0         0       58       635  ...                  7             0   
1         1       38        11  ...                  5             0   
2         0       26       426  ...                  4             0   
3         0       26        11  ...                  6             0   
4         0       94       173  ...                  5             0   

   AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  \
0             0             0             0             0         0   
1             0             0             0             0         0   
2             0             0             0             0         0   
3             0             0             0             0         0   
4             0             0             0             0         0   

   Z_CostContact  Z_Revenue  Response  
0              3         11         1  
1              3         11         0  
2              3         11         0  
3              3         11         0  
4              3         11         0  

[5 rows x 29 columns]

## Graphics


In [11]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)


In [12]:

fig = make_subplots(rows=1, cols=3, specs=[
                    [{"type": "pie"}, {"type": "pie"}, {"type": "pie"}]])

fig.update_layout(
    width=750,
    height=500,
    autosize=False,
    margin=dict(t=100, b=0, l=0, r=0),
    annotations=[dict(text='Education<br>Level', x=0.09, y=0.5, font_size=12, showarrow=False),
                 dict(text='Living<br>Status', x=0.50,
                      y=0.5, font_size=12, showarrow=False),
                 dict(text='Customer<br>Age', x=0.91, y=0.5, font_size=12, showarrow=False)]
)

for idx, col in enumerate(['Education_Level', 'Living_Status', 'Cust_Age']):
    fig.add_trace(go.Pie(
        values=data[col].value_counts().values,
        labels=data[col].value_counts().index,
        hole=0.5,
        hovertemplate="%{label} <br>Value: %{value}<extra></extra>",
        name=col),
        row=1, col=idx+1)

fig.show()


In [13]:
product_columns = ['MntWines', 'MntFruits', 'MntMeatProducts',
                   'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']
products_count = []

for product in product_columns:
    products_count.append(data[product].sum())

# graph

labels = ['Wines', 'Fruits', 'Meat Products',
          'Fish Products', 'Sweet Products', 'Gold Products']
values = products_count

fig = go.Figure(data=[go.Pie(
    values=values,
    labels=labels,
    hovertemplate="%{label} <br>Value: %{value}<extra></extra>")])

fig.update_layout(
    width=750,
    height=500,
    autosize=False,
    margin=dict(t=100, b=0, l=0, r=0),
)

fig.show()


In [14]:
purchase_types = ['NumDealsPurchases', 'NumWebPurchases',
                  'NumCatalogPurchases', 'NumStorePurchases']
purchase_count = []

for purchase in purchase_types:
    purchase_count.append(data[purchase].sum())

# graph

labels = ['Deal', 'Web', 'Catalog', 'Store']
values = purchase_count

fig = go.Figure(data=[go.Pie(
    values=values,
    labels=labels,
    hovertemplate="%{label} <br>Value: %{value}<extra></extra>")])

fig.update_layout(
    width=750,
    height=500,
    autosize=False,
    margin=dict(t=100, b=0, l=0, r=0),
)

fig.show()


## Model


#### Preproccesing for models


In [15]:
model_data = data.drop(['ID', 'Z_CostContact', 'Z_Revenue'], axis=1)

# reordering columns

column_names = ['Education_Level', 'Living_Status', 'Age', 'Cust_Age', 'Income',
                'Kidhome', 'Teenhome', 'Recency', 'MntWines', 'MntFruits',
                'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
                'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
                'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
                'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
                'AcceptedCmp2', 'Complain', 'Response']

column_names_reordered = ['Education_Level', 'Living_Status', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
                          'AcceptedCmp2', 'Complain', 'Age', 'Cust_Age', 'Income',
                          'Kidhome', 'Teenhome', 'Recency', 'MntWines', 'MntFruits',
                          'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
                          'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
                          'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth', 'Response']

model_data = model_data[column_names_reordered]
model_data.head()


Education_Level       Living_Status  AcceptedCmp3  AcceptedCmp4  \
0            High  Living with Others             0             0   
1            High  Living with Others             0             0   
2            High  Living with Others             0             0   
3            High  Living with Others             0             0   
4            High  Living with Others             0             0   

   AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  Age  Cust_Age  ...  \
0             0             0             0         0   66        10  ...   
1             0             0             0         0   69         9  ...   
2             0             0             0         0   58         9  ...   
3             0             0             0         0   39         9  ...   
4             0             0             0         0   42         9  ...   

   MntMeatProducts  MntFishProducts  MntSweetProducts  MntGoldProds  \
0              546              172                88            88   
1                6                2                 1             6   
2              127              111                21            42   
3               20               10                 3             5   
4              118               46                27            15   

   NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  NumStorePurchases  \
0                  3                8                   10                  4   
1                  2                1                    1                  2   
2                  1                8                    2                 10   
3                  2                2                    0                  4   
4                  5                5                    3                  6   

   NumWebVisitsMonth  Response  
0                  7         1  
1                  5         0  
2                  4         0  
3                  6         0  
4                  5         0  

[5 rows x 26 columns]

In [16]:
x = model_data.iloc[:, :-1].values
y = model_data.iloc[:, -1].values


In [17]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)


In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct_edu = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x_train = np.array(ct_edu.fit_transform(x_train))
x_test = np.array(ct_edu.fit_transform(x_test))
print(x_train)


[[0.0 0.0 1.0 ... 1 2 6]
 [1.0 0.0 0.0 ... 4 7 6]
 [1.0 0.0 0.0 ... 11 5 2]
 ...
 [1.0 0.0 0.0 ... 3 5 1]
 [0.0 1.0 0.0 ... 0 4 6]
 [1.0 0.0 0.0 ... 6 11 5]]


In [19]:
ct_ls = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x_train = np.array(ct_ls.fit_transform(x_train))
x_test = np.array(ct_ls.fit_transform(x_test))
print(x_train)


[[0.0 1.0 0.0 ... 1 2 6]
 [0.0 1.0 1.0 ... 4 7 6]
 [0.0 1.0 1.0 ... 11 5 2]
 ...
 [0.0 1.0 1.0 ... 3 5 1]
 [0.0 1.0 0.0 ... 0 4 6]
 [0.0 1.0 1.0 ... 6 11 5]]


In [20]:
x_train[0]


array([0.0, 1.0, 0.0, 0.0, 1.0, 1, 0, 0, 0, 0, 0, 45, 10, 24882.0, 1, 0,
       52, 1, 4, 10, 29, 0, 36, 1, 1, 1, 2, 6], dtype=object)

In [21]:
y_train

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [22]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train[:, 11:] = sc.fit_transform(x_train[:, 11:])
x_test[:, 11:] = sc.fit_transform(x_test[:, 11:])
x_train[0]


array([0.0, 1.0, 0.0, 0.0, 1.0, 1, 0, 0, 0, 0, 0, -0.7749517209748122,
       1.2369289643939685, -1.0658709206915034, 1.0417383164124536,
       -0.9328151443962748, 0.11005340356189235, -0.9058571073056304,
       -0.5534515460364157, -0.6912570347605163, -0.15265256589162382,
       -0.6498109270035145, -0.14644261101084666, -0.6814991231392435,
       -1.083110853639455, -0.5714668414372226, -1.1566379404221405,
       0.2898515448693941], dtype=object)

#### Logistic Regression


In [23]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(random_state=0)
lr.fit(x_train, y_train)


LogisticRegression(random_state=0)

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score

y_pred = lr.predict(x_test)

print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred)



[[368  12]
 [ 41  27]]


0.8816964285714286

In [25]:
y_train

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

#### Support Vector Machines


In [26]:
from sklearn.svm import SVC

classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(x_train, y_train)

y_pred_svc = classifier.predict(x_test)

print(confusion_matrix(y_test, y_pred_svc))
accuracy_score(y_test, y_pred_svc)


[[371   9]
 [ 49  19]]


0.8705357142857143

In [27]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator=classifier,
                           param_grid=parameters,
                           scoring='accuracy',
                           cv=10,
                           n_jobs=-1)
grid_search.fit(x_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)


Best Accuracy: 88.73 %
Best Parameters: {'C': 1, 'kernel': 'linear'}


#### Random Forest


In [28]:
from sklearn.ensemble import RandomForestRegressor
# Create the parameter grid based on the results of random search
parameters = {
    'n_estimators': [10, 20, 50, 100, 150, 200, 250, 300],
    'max_depth': [1, 2, 3, 4],
}
regr = RandomForestRegressor(random_state=0)

clf = GridSearchCV(regr, parameters)
clf.fit(x_train, y_train)


GridSearchCV(estimator=RandomForestRegressor(random_state=0),
             param_grid={'max_depth': [1, 2, 3, 4],
                         'n_estimators': [10, 20, 50, 100, 150, 200, 250, 300]})

In [29]:
print(clf.best_params_)

print(clf.best_estimator_)

best_accuracy = clf.best_score_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))


{'max_depth': 4, 'n_estimators': 100}
RandomForestRegressor(max_depth=4, random_state=0)
Best Accuracy: 24.11 %


#### Naive Bayes


In [30]:
from sklearn.naive_bayes import GaussianNB

cls_nb = GaussianNB()
cls_nb.fit(x_train, y_train)
y_pred_nb = cls_nb.predict(x_test)

print(confusion_matrix(y_test, y_pred_nb))
accuracy_score(y_test, y_pred_nb)


[[337  43]
 [ 38  30]]


0.8191964285714286